// lib/phrases.js
// UI 텍스트
export const UIL10N = {
  ko: { trending: "요즘 많이 찾는 카테고리" },
  en: { trending: "Trending Categories" },
  ja: { trending: "人気のカテゴリ" },
  zh: { trending: "热门分类" },
};

// 카테고리 메타
export const CATEGORIES = [
  { id: "greet",     icon: "👋", name:{ko:"인사/기본", en:"Basics", ja:"挨拶・基本", zh:"问候/基础"}, hint:{ko:"처음 만남·예의", en:"First contact", ja:"初対面・礼儀", zh:"初次见面·礼貌"} },
  { id: "transport", icon: "🚕", name:{ko:"교통", en:"Transport", ja:"交通", zh:"交通"}, hint:{ko:"택시·대중교통", en:"Taxi & transit", ja:"タクシー・電車", zh:"出租车/地铁"} },
  { id: "stay",      icon: "🏨", name:{ko:"숙소", en:"Stay", ja:"宿泊", zh:"住宿"}, hint:{ko:"체크인·와이파이", en:"Check-in & Wi-Fi", ja:"チェックイン・Wi-Fi", zh:"入住/Wi-Fi"} },
  { id: "food",      icon: "🍜", name:{ko:"식당", en:"Food", ja:"飲食", zh:"餐饮"}, hint:{ko:"주문·알레르기", en:"Order & allergy", ja:"注文・アレルギー", zh:"点餐/过敏"} },
  { id: "shopping",  icon: "🛍️", name:{ko:"쇼핑", en:"Shopping", ja:"買い物", zh:"购物"}, hint:{ko:"가격·환불", en:"Price & refund", ja:"値段・返品", zh:"价格/退货"} },
  { id: "direction", icon: "🧭", name:{ko:"길찾기", en:"Directions", ja:"道案内", zh:"问路"}, hint:{ko:"지도·길", en:"Map & way", ja:"地図・道", zh:"地图/路线"} },
  { id: "emergency", icon: "🚑", name:{ko:"비상/병원", en:"Emergency", ja:"緊急・病院", zh:"紧急/医院"}, hint:{ko:"도움 요청", en:"Ask for help", ja:"助けて", zh:"求助"} },
  { id: "money",     icon: "💳", name:{ko:"금융/통신", en:"Money/Phone", ja:"お金・通信", zh:"金融/通信"}, hint:{ko:"환전·심/e심", en:"Exchange & SIM", ja:"両替・SIM", zh:"换汇/SIM"} },
  { id: "sight",     icon: "🏛️", name:{ko:"관광", en:"Sightseeing", ja:"観光", zh:"观光"}, hint:{ko:"입장·시간", en:"Tickets & hours", ja:"入場・時間", zh:"门票/时间"} },
  { id: "etc",       icon: "✨", name:{ko:"기타/문화", en:"Etc./Culture", ja:"その他・文化", zh:"其它/文化"}, hint:{ko:"매너·소통", en:"Manners & misc.", ja:"マナーなど", zh:"礼仪/其它"} },
];

// 헬퍼
const P = (id, catId, ko, en, ja, zh, rko="", ren="", rja="", rzh="") => ({
  id, catId, ko, en, ja, zh, roman: { ko: rko || en, en: ren || en, ja: rja || ja, zh: rzh || zh }
});

// ====== 100개 문장 ======
export const PHRASES = [
  // greet (10)
  P("greet-01","greet","안녕하세요","Hello","こんにちは","你好",
    "annyeong-haseyo","Hello","konnichiwa","ni hao"),
  P("greet-02","greet","좋은 아침입니다","Good morning","おはようございます","早上好",
    "joeun achim-imnida","Good morning","ohayō gozaimasu","zao shang hao"),
  P("greet-03","greet","안녕히 주무세요","Good night","おやすみなさい","晚安",
    "annyeonghi jumuseyo","Good night","oyasuminasai","wan an"),
  P("greet-04","greet","감사합니다","Thank you","ありがとうございます","谢谢",
    "gamsa-hamnida","Thank you","arigatō gozaimasu","xie xie"),
  P("greet-05","greet","부탁합니다","Please","お願いします","请",
    "butak-hamnida","Please","onegai shimasu","qing"),
  P("greet-06","greet","죄송합니다","Sorry","すみません／ごめんなさい","对不起",
    "joesong-hamnida","Sorry","sumimasen / gomen nasai","dui bu qi"),
  P("greet-07","greet","실례합니다","Excuse me","失礼します","劳驾/不好意思",
    "sillye-hamnida","Excuse me","shitsurei shimasu","lao jia / bu hao yi si"),
  P("greet-08","greet","저는 ○○입니다","I’m ○○","私は○○です","我叫○○",
    "jeoneun ○○-imnida","I'm ○○","watashi wa ○○ desu","wo jiao ○○"),
  P("greet-09","greet","만나서 반갑습니다","Nice to meet you","はじめまして","很高兴见到你",
    "mannaseo bangapseumnida","Nice to meet you","hajimemashite","hen gaoxing jian dao ni"),
  P("greet-10","greet","괜찮아요","It’s okay","大丈夫です","没关系",
    "gwaenchanayo","It's okay","daijōbu desu","mei guan xi"),

  // transport (10)
  P("trans-01","transport","택시 불러 주세요","Please call a taxi","タクシーを呼んでください","请帮我叫出租车",
    "taeksi bulleo juseyo","Please call a taxi","takushii o yonde kudasai","qing bang wo jiao chu zu che"),
  P("trans-02","transport","공항까지 얼마예요?","How much to the airport?","空港までいくらですか？","到机场多少钱？",
    "gonghang kkaji eolmayeyo?","How much to the airport?","kuukou made ikura desu ka?","dao ji chang duo shao qian?"),
  P("trans-03","transport","이 버스 ○○에 가요?","Does this bus go to ○○?","このバスは○○へ行きますか？","这班车去○○吗？",
    "i beoseu ○○-e gayo?","Does this bus go to ○○?","kono basu wa ○○ e ikimasu ka?","zhe ban che qu ○○ ma?"),
  P("trans-04","transport","표 한 장 주세요","One ticket, please","切符を一枚ください","请给我一张票",
    "pyo han jang juseyo","One ticket, please","kippu o ichimai kudasai","qing gei wo yi zhang piao"),
  P("trans-05","transport","다음 정류장에 내려요","I get off at next stop","次の停留所で降ります","下一站下车",
    "daeum jeongryujang-e naeryeoyo","I get off at next stop","tsugi no teiryuujo de orimasu","xia yi zhan xia che"),
  P("trans-06","transport","미터기로 가 주세요","Use the meter, please","メーターでお願いします","请打表",
    "miteogi-ro ga juseyo","Use the meter, please","meeta de onegai shimasu","qing da biao"),
  P("trans-07","transport","좌석 있나요?","Any seats available?","空席はありますか？","有座位吗？",
    "jwaseok innayo?","Any seats available?","kuuseki wa arimasu ka?","you zuo wei ma?"),
  P("trans-08","transport","짐 보관할 수 있나요?","Can I store luggage?","荷物を預けられますか？","可以寄存行李吗？",
    "jim bogwanhal su innayo?","Can I store luggage?","nimotsu o azukeraremasu ka?","ke yi ji cun xing li ma?"),
  P("trans-09","transport","길 좀 추천해 주세요","Which route is better?","どのルートが良いですか？","哪条路线更好？",
    "gil jom chucheonhae juseyo","Which route is better?","dono ruuto ga yoi desu ka?","na tiao lu xian geng hao?"),
  P("trans-10","transport","길이 막혀요?","Is there heavy traffic?","渋滞していますか？","堵车吗？",
    "giri makyeoyo?","Is there heavy traffic?","juutai shiteimasu ka?","du che ma?"),

  // stay (10)
  P("stay-01","stay","체크인 하려고 합니다","I’d like to check in","チェックインをお願いします","我想办理入住",
    "chekeu-in haryeogo hamnida","I'd like to check in","chekkuin o onegai shimasu","wo xiang banli ruzhu"),
  P("stay-02","stay","체크아웃 하겠습니다","I’ll check out","チェックアウトします","我要退房",
    "chekeu-aus hagetseumnida","I'll check out","chekkuauto shimasu","wo yao tui fang"),
  P("stay-03","stay","와이파이 비밀번호는요?","What’s the Wi-Fi password?","Wi-Fiのパスワードは？","Wi-Fi 密码是多少？",
    "wai-pai bimilbeonho neunyo?","What's the Wi-Fi password?","waifai no pasuwaado wa?","wifi mi ma shi duo shao?"),
  P("stay-04","stay","조식 포함인가요?","Is breakfast included?","朝食は含まれますか？","含早餐吗？",
    "josik poham ingayo?","Is breakfast included?","choushoku wa fukuma remasu ka?","han zao can ma?"),
  P("stay-05","stay","하루 더 연장할게요","I’d like to extend one night","一泊延長したいです","再住一天",
    "haru deo yeonjanghalgeyo","I'd like to extend one night","ippaku enchou shitai desu","zai zhu yi tian"),
  P("stay-06","stay","조용한 방으로 부탁해요","A quiet room, please","静かな部屋をお願いします","安静的房间",
    "joyonghan bang-euro butakaeyo","A quiet room, please","shizuka na heya o onegai shimasu","an jing de fang jian"),
  P("stay-07","stay","에어컨이 고장났어요","The AC is broken","エアコンが壊れています","空调坏了",
    "eeokeoni gojang-nasseoyo","The AC is broken","eakon ga kowarete imasu","kong tiao huai le"),
  P("stay-08","stay","수건 좀 더 주세요","More towels, please","タオルを追加してください","请再给毛巾",
    "sugeon jom deo juseyo","More towels, please","taoru o tsuika shite kudasai","qing zai gei mao jin"),
  P("stay-09","stay","금고를 사용하고 싶어요","I want to use the safe","セーフを使いたいです","我想用保险箱",
    "geumgoreul sayonghago sipeoyo","I want to use the safe","seefu o tsukaitai desu","wo xiang yong bao xian xiang"),
  P("stay-10","stay","짐 보관 가능할까요?","Can you keep my luggage?","荷物を預かってもらえますか？","可以寄存行李吗？",
    "jim bogwan ganeunghalkkayo?","Can you keep my luggage?","nimotsu o azukatte moraemasu ka?","ke yi ji cun xing li ma?"),

  // food (10)
  P("food-01","food","메뉴판 주세요","Menu, please","メニューをください","请给我菜单",
    "menyupan juseyo","Menu, please","menyuu o kudasai","qing gei wo cai dan"),
  P("food-02","food","추천 메뉴는?","Any recommendation?","おすすめは何ですか？","有什么推荐？",
    "chucheon menyuneun?","Any recommendation?","osusume wa nan desu ka?","you shen me tui jian?"),
  P("food-03","food","맵지 않게 해 주세요","Not spicy, please","辛くしないでください","不要太辣",
    "maepji anke hae juseyo","Not spicy, please","karaku shinaide kudasai","bu yao tai la"),
  P("food-04","food","덜 달게 해 주세요","Less sweet, please","甘さ控えめで","少放糖",
    "deol dalge hae juseyo","Less sweet, please","amasa hikaeme de","shao fang tang"),
  P("food-05","food","알레르기가 있어요","I have an allergy","アレルギーがあります","我有过敏",
    "allereugi-ga isseoyo","I have an allergy","arerugii ga arimasu","wo you guo min"),
  P("food-06","food","포장해 주세요","To go, please","テイクアウトでお願いします","打包带走",
    "pojanghae juseyo","To go, please","teikuauto de onegai shimasu","da bao dai zou"),
  P("food-07","food","이거 채식 메뉴예요?","Is this vegetarian?","ベジタリアン向けですか？","是素食吗？",
    "igeo chaesik menyu-yeyo?","Is this vegetarian?","bejitarian muke desu ka?","shi su shi ma?"),
  P("food-08","food","물 좀 주세요","Water, please","お水をお願いします","请给我水",
    "mul jom juseyo","Water, please","omizu o onegai shimasu","qing gei wo shui"),
  P("food-09","food","계산서 주세요","Check, please","お会計お願いします","请结账",
    "gyesanseo juseyo","Check, please","okaikei onegai shimasu","qing jie zhang"),
  P("food-10","food","팁은 포함됐나요?","Is tip included?","チップは含まれていますか？","包含小费吗？",
    "tibeun poham dwaennayo?","Is tip included?","chippu wa fukuma rete imasu ka?","bao han xiao fei ma?"),

  // shopping (10)
  P("shop-01","shopping","이거 얼마예요?","How much is this?","これはいくらですか？","这个多少钱？",
    "igeo eolmayeyo?","How much is this?","kore wa ikura desu ka?","zhe ge duo shao qian?"),
  P("shop-02","shopping","좀 깎아 주세요","Can you discount?","まけてもらえますか？","可以便宜点吗？",
    "jom kkakka juseyo","Can you discount?","makete moraemasu ka?","ke yi pian yi dian ma?"),
  P("shop-03","shopping","카드 결제 가능해요?","Do you take card?","カードは使えますか？","可以刷卡吗？",
    "kadeu gyeolje ganeunghaeyo?","Do you take card?","kaado wa tsukae masu ka?","ke yi shua ka ma?"),
  P("shop-04","shopping","영수증 주세요","Receipt, please","レシートをください","请给收据",
    "yeongsujeung juseyo","Receipt, please","reshiito o kudasai","qing gei shou ju"),
  P("shop-05","shopping","환불 가능해요?","Can I get a refund?","返金できますか？","可以退款吗？",
    "hwanbul ganeunghaeyo?","Can I get a refund?","henkin dekimasu ka?","ke yi tui kuan ma?"),
  P("shop-06","shopping","교환하고 싶어요","I want to exchange","交換したいです","想换货",
    "gyohwanhago sipeoyo","I want to exchange","koukan shitai desu","xiang huan huo"),
  P("shop-07","shopping","시착해도 되나요?","May I try it on?","試着してもいいですか？","可以试穿吗？",
    "sichakhaedo doenayo?","May I try it on?","shichaku shite mo ii desu ka?","ke yi shi chuan ma?"),
  P("shop-08","shopping","다른 색 있어요?","Do you have other colors?","他の色はありますか？","有别的颜色吗？",
    "dareun saek isseoyo?","Do you have other colors?","hoka no iro wa arimasu ka?","you bie de yan se ma?"),
  P("shop-09","shopping","포장해 주세요","Please wrap it","包んでください","请包装",
    "pojanghae juseyo","Please wrap it","tsutsunde kudasai","qing bao zhuang"),
  P("shop-10","shopping","면세 가능해요?","Tax-free available?","免税できますか？","可以免税吗？",
    "myeonse ganeunghaeyo?","Tax-free available?","menzei dekimasu ka?","ke yi mian shui ma?"),

  // direction (10)
  P("dir-01","direction","○○는 어디예요?","Where is ○○?","○○はどこですか？","○○在哪里？",
    "○○neun eodi-yeyo?","Where is ○○?","○○ wa doko desu ka?","○○ zai na li?"),
  P("dir-02","direction","왼쪽/오른쪽으로 가세요","Go left/right","左/右へ行ってください","请向左/右走",
    "oenjjok / oreunjjog-euro gaseyo","Go left/right","hidari / migi e itte kudasai","qing xiang zuo / you zou"),
  P("dir-03","direction","직진하세요","Go straight","まっすぐ進んでください","请直走",
    "jikjin haseyo","Go straight","massugu susunde kudasai","qing zhi zou"),
  P("dir-04","direction","가까운 지하철역은?","Nearest subway?","最寄りの地下鉄は？","最近的地铁站？",
    "gakkaun jihacheol yeogeun?","Nearest subway?","moyori no chikatetsu wa?","zui jin de di tie zhan?"),
  P("dir-05","direction","이 주소로 가 주세요","Take me to this address","この住所へお願いします","请去这个地址",
    "i juso-ro ga juseyo","Take me to this address","kono juusho e onegai shimasu","qing qu zhe ge di zhi"),
  P("dir-06","direction","지도에 표시해 주세요","Please mark on the map","地図に印を付けてください","请在地图上标注",
    "jido-e pyosihae juseyo","Please mark on the map","chizu ni shirushi o tsukete kudasai","qing zai di tu shang biao zhu"),
  P("dir-07","direction","몇 분 걸려요?","How long does it take?","どのくらいかかりますか？","要多久？",
    "myeot bun geollyeoyo?","How long does it take?","dono kurai kakarimasu ka?","yao duo jiu?"),
  P("dir-08","direction","입구는 어디예요?","Where is the entrance?","入口はどこですか？","入口在哪里？",
    "ipguneun eodi-yeyo?","Where is the entrance?","iriguchi wa doko desu ka?","ru kou zai na li?"),
  P("dir-09","direction","길을 잃었어요","I’m lost","道に迷いました","我迷路了",
    "gireul ilheosseoyo","I'm lost","michi ni mayoi mashita","wo mi lu le"),
  P("dir-10","direction","가까운 화장실은?","Nearest restroom?","一番近いトイレは？","最近的洗手间？",
    "gakkaun hwajangsil-eun?","Nearest restroom?","ichiban chikai toire wa?","zui jin de xi shou jian?"),

  // emergency (10)
  P("em-01","emergency","도와주세요!","Help!","助けて！","救命！",
    "dowajuseyo!","Help!","tasukete!","jiu ming!"),
  P("em-02","emergency","경찰을 불러 주세요","Call the police","警察を呼んでください","请叫警察",
    "gyeongchareul bulleo juseyo","Call the police","keisatsu o yonde kudasai","qing jiao jing cha"),
  P("em-03","emergency","구급차가 필요해요","I need an ambulance","救急車をお願いします","请叫救护车",
    "gugeupchaga pil-yohaeyo","I need an ambulance","kyuukyuusha o onegai shimasu","qing jiao jiu hu che"),
  P("em-04","emergency","병원에 가야 해요","I need a hospital","病院に行く必要があります","我要去医院",
    "byeongwon-e gaya haeyo","I need a hospital","byouin ni iku hitsuyou ga arimasu","wo yao qu yi yuan"),
  P("em-05","emergency","여권을 잃어버렸어요","I lost my passport","パスポートを失くしました","护照丢了",
    "yeogwoneul ireobeoryeosseoyo","I lost my passport","pasupooto o nakushimashita","hu zhao diu le"),
  P("em-06","emergency","소매치기 당했어요","I was pickpocketed","スリに遭いました","被偷了",
    "somaechigi danghaesseoyo","I was pickpocketed","suri ni aimashita","bei tou le"),
  P("em-07","emergency","아파요","I’m in pain","痛いです","我很痛",
    "apayo","I'm in pain","itai desu","wo hen tong"),
  P("em-08","emergency","약국은 어디예요?","Where is a pharmacy?","薬局はどこですか？","药店在哪里？",
    "yakkug-eun eodi-yeyo?","Where is a pharmacy?","yakkyoku wa doko desu ka?","yao dian zai na li?"),
  P("em-09","emergency","알레르기가 있어요","I have an allergy","アレルギーがあります","我有过敏",
    "allereugi-ga isseoyo","I have an allergy","arerugii ga arimasu","wo you guo min"),
  P("em-10","emergency","연락해야 할 번호는?","Emergency number?","緊急番号は？","急救电话是多少？",
    "yeonrakhaya hal beonhoneun?","Emergency number?","kinkyuu bangou wa?","jiu jiu dian hua shi duo shao?"),

  // money (10)
  P("mon-01","money","환전하고 싶어요","I’d like to exchange money","両替したいです","我想换钱",
    "hwanjeonhago sipeoyo","I'd like to exchange money","ryougae shitai desu","wo xiang huan qian"),
  P("mon-02","money","환율이 어떻게 돼요?","What’s the rate?","レートはいくらですか？","汇率是多少？",
    "hwanyuri eotteoke dwaeyo?","What's the rate?","reeto wa ikura desu ka?","hui lv shi duo shao?"),
  P("mon-03","money","ATM은 어디예요?","Where is an ATM?","ATMはどこですか？","ATM在哪里？",
    "ATM-eun eodi-yeyo?","Where is an ATM?","ee-tee-em wa doko desu ka?","ATM zai na li?"),
  P("mon-04","money","현금 인출이 안 돼요","Can’t withdraw cash","引き出せません","无法取现",
    "hyeongeum inchuri an dwaeyo","Can't withdraw cash","hikidase masen","wu fa qu xian"),
  P("mon-05","money","영수증 이메일로 주세요","Send receipt by email","レシートをメールでください","收据发我邮箱",
    "yeongsujeung imeillo juseyo","Send receipt by email","reshiito o meeru de kudasai","shou ju fa wo you xiang"),
  P("mon-06","money","유심/e심은 어디서 사요?","Where to buy SIM/eSIM?","SIM/eSIMはどこで買えますか？","在哪里买SIM/eSIM？",
    "yusim / isim eun eodiseo sayo?","Where to buy SIM/eSIM?","shimu / i-shimu wa doko de kaemasu ka?","zai na li mai SIM / eSIM?"),
  P("mon-07","money","데이터 요금제 추천해 주세요","Recommend a data plan","データプランをおすすめしてください","推荐流量套餐",
    "deiteo yogeumje chucheonhae juseyo","Recommend a data plan","deeta puran o osusume shite kudasai","tui jian liu liang tao can"),
  P("mon-08","money","충전이 필요해요","I need to top up","チャージが必要です","需要充值",
    "chungjeoni piryohaeyo","I need to top up","chaaji ga hitsuyou desu","xu yao chong zhi"),
  P("mon-09","money","인터넷이 안 돼요","No internet","インターネットが使えません","上不了网",
    "inteonet-i an dwaeyo","No internet","intaaneet to ga tsukae masen","shang bu liao wang"),
  P("mon-10","money","국제전화 어떻게 해요?","How to make an intl call?","国際電話はどうかけますか？","如何打国际电话？",
    "gukjejeonhwa eotteoke haeyo?","How to make an international call?","kokusai denwa wa dou kakemasu ka?","ru he da guo ji dian hua?"),

  // sight (10)
  P("sight-01","sight","입장권 두 장 주세요","Two tickets, please","入場券を2枚ください","请给两张门票",
    "ipjanggwon du jang juseyo","Two tickets, please","nyuujouken o nimai kudasai","qing gei liang zhang men piao"),
  P("sight-02","sight","개장/폐장 시간은?","Opening/closing time?","開館/閉館時間は？","开放/关闭时间？",
    "gaejang/pejang siganeun?","Opening/closing time?","kaikan / heikan jikan wa?","kai fang / guan bi shi jian?"),
  P("sight-03","sight","가이드 투어 있나요?","Do you have a guided tour?","ガイドツアーはありますか？","有讲解团吗？",
    "gaideu tuo eo innayo?","Do you have a guided tour?","gaido tsuaa wa arimasu ka?","you jiang jie tuan ma?"),
  P("sight-04","sight","오디오 가이드는요?","Audio guide?","オーディオガイドは？","有语音导览吗？",
    "odio gaideu neunyo?","Audio guide?","oodio gaido wa?","you yu yin dao lan ma?"),
  P("sight-05","sight","사진 촬영 가능해요?","May I take photos?","写真撮影は可能ですか？","可以拍照吗？",
    "sajin chwal-yeong ganeunghaeyo?","May I take photos?","shashin satsuei wa kanou desu ka?","ke yi pai zhao ma?"),
  P("sight-06","sight","대기 시간이 얼마나 되나요?","How long is the wait?","待ち時間はどのくらい？","需要等多久？",
    "daegi sigan-i eolmana doenayo?","How long is the wait?","machi jikan wa dono kurai?","xu yao deng duo jiu?"),
  P("sight-07","sight","예약했어요/예약 없어요","I have/don’t have a reservation","予約あり/なしです","有预约/没预约",
    "yeyakhess-eoyo / yeyak eopseoyo","I have / don't have a reservation","yoyaku ari / nashi desu","you yu yue / mei yu yue"),
  P("sight-08","sight","기념품 가게는 어디예요?","Where is the gift shop?","お土産ショップはどこ？","纪念品店在哪？",
    "ginyeompum gageneun eodi-yeyo?","Where is the gift shop?","omiyage shoppu wa doko?","ji nian pin dian zai na?"),
  P("sight-09","sight","한가한 시간은 언제예요?","Less crowded time?","空いている時間帯は？","人少的时间？",
    "hangahan sigan-eun eonje-yeyo?","Less crowded time?","suite iru jikan-tai wa?","ren shao de shi jian?"),
  P("sight-10","sight","줄은 어디에서 서요?","Where is the line?","列はどこに並びますか？","在哪里排队？",
    "jureun eodieseo seoyo?","Where is the line?","retsu wa doko ni narabimasu ka?","zai na li pai dui?"),

  // etc (10)
  P("etc-01","etc","사진 같이 찍어도 될까요?","Can we take a photo?","一緒に写真を撮ってもいいですか？","可以一起拍照吗？",
    "sajin gachi jjigeodo doelkkayo?","Can we take a photo?","issho ni shashin o totte mo ii desu ka?","ke yi yi qi pai zhao ma?"),
  P("etc-02","etc","현지 추천 장소가 있나요?","Any local tips?","おすすめスポットは？","有什么本地推荐？",
    "hyeonji chucheon jangso-ga innayo?","Any local tips?","osusume supotto wa?","you shen me ben di tui jian?"),
  P("etc-03","etc","와이파이 있나요?","Do you have Wi-Fi?","Wi-Fiはありますか？","有Wi-Fi吗？",
    "wai-pai innayo?","Do you have Wi-Fi?","waifai wa arimasu ka?","you wifi ma?"),
  P("etc-04","etc","휴대폰 충전해도 될까요?","Can I charge my phone?","充電してもいいですか？","能充电吗？",
    "hyudaepon chungjeon haedo doelkkayo?","Can I charge my phone?","juuden shite mo ii desu ka?","neng chong dian ma?"),
  P("etc-05","etc","흡연 구역은 어디예요?","Where is the smoking area?","喫煙所はどこ？","吸烟区在哪里？",
    "heubyeon guyeogeun eodi-yeyo?","Where is the smoking area?","kitsuenjo wa doko?","xi yan qu zai na li?"),
  P("etc-06","etc","줄 서는 곳이 어디죠?","Where do I line up?","並ぶ場所はどこ？","在哪排队？",
    "jul se-neun gosi eodijyo?","Where do I line up?","narabu basho wa doko?","zai na pai dui?"),
  P("etc-07","etc","사진 보내 드릴게요","I’ll send you the photo","写真を送ります","把照片发给你",
    "sajin bonae deurilgeyo","I'll send you the photo","shashin o okurimasu","ba zhao pian fa gei ni"),
  P("etc-08","etc","천천히 말해 주세요","Please speak slowly","ゆっくり話してください","请说慢一点",
    "cheoncheonhi malhae juseyo","Please speak slowly","yukkuri hanashite kudasai","qing shuo man yi dian"),
  P("etc-09","etc","추천 음식은 뭐예요?","What do you recommend to eat?","おすすめの料理は？","你推荐什么菜？",
    "chucheon eumsigeun mwoyeyo?","What do you recommend to eat?","osusume no ryouri wa?","ni tui jian shen me cai?"),
  P("etc-10","etc","괜찮으시면 연락 주세요","Please contact me if okay","よければ連絡ください","方便的话联系我",
    "gwaenchan-eusimyeon yeollak juseyo","Please contact me if okay","yokereba renraku kudasai","fang bian de hua lian xi wo"),
];
